### ISSUE TITLE
feat: ipfs gateway for origin

### ISSUE THREAD

**Issue by theBeardA** [fleek-network/ursa#134]
As a starting point for origin, we will cache miss into IPFS gateway if the content is not on the network.
there are ideas behind the origin field in the metadata but that can be tackled with another issue when we start integrating storage protocols

**Comment by b0xtch** [comment]
This requires more discussion; the initial idea is to cache miss into ipfs gateway/filecoin/arweave gateway. We can start with ipfs gateway and then move to integrate other protocols each with different reqs.

**Comment by ozwaldorf** [comment]
would the cache miss be before or after bitswap query?

Would the following be correct?

1. (not impl - lru cache)
2. internal bitswap store
3. bitswap query to connected nodes/check bloom filter
4. cache miss
    - ipfs
    - arweave
    - etc

**Comment by b0xtch** [comment]
> would the cache miss be before or after bitswap query?
> 
> Would the following be correct?
> 
> 1. (not impl - lru cache)
> 2. internal bitswap store
> 3. bitswap query to connected nodes/check bloom filter
> 4. cache miss
>    
>    * ipfs
>    * arweave
>    * etc

Before

**Comment by ozwaldorf** [comment]
Should gateways be configurable?
