### ISSUE TITLE
chore: programmatic update config

### ISSUE THREAD

**Issue by theBeardA** [fleek-network/ursa#135]
If a new field is added to config or the type of any field is changed in the config. The start of the node would error out since the current config stored in `.ursa/config.toml` file is not going to match the `UrsaConfig` structure in the newer version of code.
Add a warning and let user choose to overwrite the current config file with the defaults. this should interactive `yes/no`.

If the user has some customize config, they need to save that somewhere to before the file is overwritten with the new config structure and defaults.

**Comment by ozwaldorf** [comment]
we could use a custom deserializer to automatically provide defaults if missing from the toml, as a first attempt, and if that fails then provide the option of full default overwrite to handle drastic config changes. If config is modified by deserializer, we can prompt the user to write out the updated config

**Comment by ozwaldorf** [comment]
something like this would work quite nicely actually:

![image](https://user-images.githubusercontent.com/8976745/210454372-6a316ccf-d90d-4ded-8b80-b596a7c050cb.png)
