### ISSUE TITLE
feat: handle cache requests from other nodes

### ISSUE THREAD

**Issue by matthias-wright** [fleek-network/ursa#214]
**Motivation:**
Each node is responsible for replicating its cached content onto its connected peers. After receiving a PUT request, a node will send a caching request to its connected peers (#193).

**TODO:**
- The cache requests have to be handled.
- For now, each node should accept a cache request (and store the corresponding content) unless the request comes from a blacklistet node.
- Accepting a cache request means getting the content (using bitswap for now) and storing it.

**Comment by kckeiks** [comment]
Closed by #224.
