### ISSUE TITLE
chore: research data transfer protocols/schemes

### ISSUE THREAD

**Issue by kckeiks** [fleek-network/ursa#273]

**Comment by kckeiks** [comment]
@matthias-wright please let me know if it's ok to close this. On my end, Botch and I have been discussing breaking changes in regards to how we handle data so I'm going to be pulling away from this work for a bit and focus on a different scope. We can reopen this in the future if needed.

**Comment by matthias-wright** [comment]
@kckeiks sure, sounds good.
