### ISSUE TITLE
research: compare cuckoo filters and bloom filters for cache summarization

### ISSUE THREAD

**Issue by matthias-wright** [fleek-network/ursa#284]
Cuckoo filters are a promising alternative to bloom filters.
They promise a better lookup performance and better space efficiency for applications requiring low false positive rates (below 3%).
This should be benchmarked and verified to determine if we should switch to cuckoo filters for our cache summarization.

**Comment by b0xtch** [comment]
This sounds interesting, could link a good reference paper for this

**Comment by matthias-wright** [comment]
This is the cuckoo filter paper: https://www.cs.cmu.edu/~dga/papers/cuckoo-conext2014.pdf

**Comment by matthias-wright** [comment]
https://docs.fleek.network/blog/bloom-and-cuckoo-filters-for-cache-summarization
