### ISSUE TITLE
chore: setting up gateway tests

### ISSUE THREAD

**Issue by ozwaldorf** [fleek-network/ursa#446]
We should have a reproducible, deployable gateway testing setup  

- beefy gateway on a rent-a-server 
- arbitrary number of DO nodes 
- Automatic setup for the nodes
- a way to put content to nodes en batch (maybe not needed once gateway supports PUT)

**Comment by b0xtch** [comment]
We have a gateway orchestration setup and terraform for arbitrary nodes

**Comment by kckeiks** [comment]
This task was completed.
