### ISSUE TITLE
Panic ERROR typed_store::rocks: error: (de)serialization error: Invalid value was given to the function

### ISSUE THREAD

**Issue by heldrida** [fleek-network/ursa#500]
# Description

Panic ERROR typed_store::rocks: error: (de)serialization error: Invalid value was given to the function

# Environment

# Demo

![image](https://user-images.githubusercontent.com/236752/231829135-9b676655-9b1e-4d94-a5ea-9004664d0732.png)

# Notes

# Checklist

- [ ] I have ensured that my version is up-to-date
- [ ] I have ensured that my issue is reproducible
- [ ] I have ensured that my issue is not a duplicate

**Comment by ozwaldorf** [comment]
#445 broke compatibility with previous existing stores. The only remedy atm is to just delete `~/.ursa/data`

**Comment by heldrida** [comment]
Created reference https://docs.fleek.network/reference/Ursa-CLI/rocksdb-deserialization-error-invalid-value-was-given-to-the-function
