### ISSUE TITLE
install fleek-network/ursa with ubuntu 22.04，got error

### ISSUE THREAD

**Issue by maclinuxp** [fleek-network/ursa#505]
# Description
 Compiling ursa v0.1.0 (/home/ubuntu/ursa/crates/ursa)
error: could not compile `ursa`

Caused by:
  process didn't exit successfully: `rustc --crate-name ursa --edition=2021 crates/ursa/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=78 --crate-type bin --emit=dep-info,link -C opt-level=z -C panic=abort -C lto -C codegen-units=1 -C debuginfo=1 -C metadata=77548d8b82666e40 -C extra-filename=-77548d8b82666e40 --out-dir /home/ubuntu/ursa/target/release/deps -C strip=debuginfo -L dependency=/home/ubuntu/ursa/target/release/deps --extern anyhow=/home/ubuntu/ursa/target/release/deps/libanyhow-89e12462c6441f2a.rlib --extern ctrlc=/home/ubuntu/ursa/target/release/deps/libctrlc-c7e13ee59fba07f2.rlib --extern dirs=/home/ubuntu/ursa/target/release/deps/libdirs-912c201a512f0746.rlib --extern dotenv=/home/ubuntu/ursa/target/release/deps/libdotenv-bec3694e74eb9e5f.rlib --extern ethers=/home/ubuntu/ursa/target/release/deps/libethers-3be294177403ff23.rlib --extern db=/home/ubuntu/ursa/target/release/deps/libforest_db-1cc1bd47ac7e29f2.rlib --extern futures=/home/ubuntu/ursa/target/release/deps/libfutures-785745ce73a546b1.rlib --extern imara_diff=/home/ubuntu/ursa/target/release/deps/libimara_diff-719aca5e19738624.rlib --extern libp2p=/home/ubuntu/ursa/target/release/deps/liblibp2p-d43d3c0cbcd3695d.rlib --extern multiaddr=/home/ubuntu/ursa/target/release/deps/libmultiaddr-d666d0d4246842a0.rlib --extern pem=/home/ubuntu/ursa/target/release/deps/libpem-0561f538023bdd7e.rlib --extern resolve_path=/home/ubuntu/ursa/target/release/deps/libresolve_path-38ea923c9a61691c.rlib --extern scopeguard=/home/ubuntu/ursa/target/release/deps/libscopeguard-a3ea72dbe8c782da.rlib --extern serde=/home/ubuntu/ursa/target/release/deps/libserde-0b474e759c39868b.rlib --extern structopt=/home/ubuntu/ursa/target/release/deps/libstructopt-bf9998c79361cdcb.rlib --extern tokio=/home/ubuntu/ursa/target/release/deps/libtokio-f5b0c82e353f8296.rlib --extern toml=/home/ubuntu/ursa/target/release/deps/libtoml-fa3ca112072d40ce.rlib --extern tracing=/home/ubuntu/ursa/target/release/deps/libtracing-e9b85a285e162af8.rlib --extern tracing_subscriber=/home/ubuntu/ursa/target/release/deps/libtracing_subscriber-984fc296cc92abb3.rlib --extern ursa_application=/home/ubuntu/ursa/target/release/deps/libursa_application-540624eeb2289098.rlib --extern ursa_consensus=/home/ubuntu/ursa/target/release/deps/libursa_consensus-1205a2af68c0b67e.rlib --extern ursa_index_provider=/home/ubuntu/ursa/target/release/deps/libursa_index_provider-f973743e699d77ab.rlib --extern ursa_metrics=/home/ubuntu/ursa/target/release/deps/libursa_metrics-014f5f3da69836e9.rlib --extern ursa_network=/home/ubuntu/ursa/target/release/deps/libursa_network-9a432c02149dd307.rlib --extern ursa_rpc_service=/home/ubuntu/ursa/target/release/deps/libursa_rpc_service-b904d05c13f71c0d.rlib --extern ursa_store=/home/ubuntu/ursa/target/release/deps/libursa_store-ef8755155f6eb307.rlib --extern ursa_telemetry=/home/ubuntu/ursa/target/release/deps/libursa_telemetry-8325b33ea50c7a0c.rlib --extern ursa_utils=/home/ubuntu/ursa/target/release/deps/libursa_utils-e4ad592924ef9d99.rlib --extern warp=/home/ubuntu/ursa/target/release/deps/libwarp-72ec08b3dedd6a1a.rlib --extern workspace_hack=/home/ubuntu/ursa/target/release/deps/libworkspace_hack-65d3bfcf01204ed9.rlib -L native=/home/ubuntu/ursa/target/release/build/ring-7ef49e6d1cdae23b/out -L native=/home/ubuntu/ursa/target/release/build/blake3-715d3a4260495d9b/out -L native=/home/ubuntu/ursa/target/release/build/blake3-715d3a4260495d9b/out -L native=/home/ubuntu/ursa/target/release/build/librocksdb-sys-43dc413a70bde72d/out -L native=/home/ubuntu/ursa/target/release/build/librocksdb-sys-43dc413a70bde72d/out -L native=/home/ubuntu/ursa/target/release/build/libz-sys-373ae87fa7b182b4/out/lib -L native=/home/ubuntu/ursa/target/release/build/libz-sys-373ae87fa7b182b4/out/lib -L native=/home/ubuntu/ursa/target/release/build/lz4-sys-03a127696ce78cb0/out -L native=/home/ubuntu/ursa/target/release/build/zstd-sys-459e7d79f40658d2/out -L native=/home/ubuntu/ursa/target/release/build/secp256k1-sys-8d43bd2291b600c9/out -L native=/home/ubuntu/ursa/target/release/build/blst-b40b1bdc37e143c2/out -L native=/home/ubuntu/ursa/target/release/build/clear_on_drop-0d36fff31717dc34/out -L native=/usr/lib/x86_64-linux-gnu -L native=/home/ubuntu/ursa/target/release/build/libnghttp2-sys-7fe8486beb21c328/out/i/lib` (signal: 9, SIGKILL: kill)
error: failed to compile `ursa v0.1.0 (/home/ubuntu/ursa/crates/ursa)`, intermediate artifacts can be found at `/home/ubuntu/ursa/target`
make: *** [Makefile:14: install] Error 101

**Comment by ozwaldorf** [comment]
> ```(signal: 9, SIGKILL: kill)
error: failed to compile ursa v0.1.0 (/home/ubuntu/ursa/crates/ursa)```

This would hint that the compilation process got killed, most likely by the kernel due to resource limitations. The project has a large number of dependencies, which takes ~8gb of ram to compile in entirety. Could you share your current specs, and if possible, try and use a machine with more ram?

**Comment by maclinuxp** [comment]
thank a lot, yes problem solved, the ram of my server just got  4 gb ,   and 8gb is ok
