### ISSUE TITLE
possible collab & code sharing with n0-computer/iroh?

### ISSUE THREAD

**Issue by b5** [fleek-network/ursa#86]
👋 fleek-folk! Congrats on your recent raise & this new project!

I work on  [iroh](https://iroh.computer) a rust implementation of IPFS (github: https://github.com/n0-computer/iroh), and looking through your codebase it might be fun to share notes, and maybe even a little bit of code 😄.

Some overlap I'm already seeing:
https://github.com/fleek-network/ursa/pull/79
https://github.com/n0-computer/iroh/pull/476

If you have any interest in chatting, I'd love to set up a call to see if there are places where we might be able to help each other out. With that said, I totally get it if y'all just need to move fast & keep things in your own codebase. If that's the case, we can always share notes!

**Comment by b0xtch** [comment]
> 👋 fleek-folk! Congrats on your recent raise & this new project!
> 
> I work on [iroh](https://iroh.computer) a rust implementation of IPFS (github: https://github.com/n0-computer/iroh), and looking through your codebase it might be fun to share notes, and maybe even a little bit of code 😄.
> 
> Some overlap I'm already seeing: #79 [n0-computer/iroh#476](https://github.com/n0-computer/iroh/pull/476)
> 
> If you have any interest in chatting, I'd love to set up a call to see if there are places where we might be able to help each other out. With that said, I totally get it if y'all just need to move fast & keep things in your own codebase. If that's the case, we can always share notes!

@b5 lets do it 💪 we would also love to pick y’all’s brain.

**Comment by b0xtch** [comment]
We had a great discussion. Closing this for now. To a fruitful collaboration 💪
